# Generated by Django 5.1.7 on 2025-03-16 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="tg_chat_id",
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name="Telergram chat_id"),
        ),
    ]
